root = "."
testdata_dir = "testdata"
tmp_dir = "bin"

[build]
args_bin = ["run", "./cmd/server/main.go", "start"]
bin = "/usr/local/go/bin/go"
delay = 500
exclude_dir = ["assets", "bin", "vendor", "testdata", "tests"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = ["cmd", "pkg", "internal"]
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = [".env"]
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 100
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[proxy]
app_port = 0
enabled = false
proxy_port = 0

[screen]
clear_on_rebuild = false
keep_scroll = true
