services:
  golang:
    container_name: sp-golang
    restart: unless-stopped
    build:
      context: ./docker/golang
      args:
        - GROUP_ID=${DOCKER_GROUP_ID}
        - USER_ID=${DOCKER_USER_ID}
    working_dir: /sparallel-server
    volumes:
      - ./:/sparallel-server
    command: [ "air", "-c", ".server.air.toml" ]
