name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: |
          CGO_ENABLED=0 GOOS=linux go build -v -a -o ./bin/sparallel_server ./cmd/server/main.go
          chmod +x ./bin/sparallel_server

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # We delete Latest tag if it exists
          git tag -d latest || true
          git push origin :refs/tags/latest || true
          # We create a new tag
          git tag -f latest
          git push -f origin latest

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ./bin/sparallel_server
          tag_name: latest
          name: Latest Build
          body: Automatically collected latest version
          token: ${{ secrets.GITHUB_TOKEN }}